client: client.o
	clang++ -Wall -o client client.o
client.o: client.cpp
	clang++ -Wall -c client.cpp
server: server.o 
	clang++ -Wall -o server server.o
server.o: server.cpp
	clang++ -Wall -c server.cpp
